// coordinates stored as [longitude, latitude] (GeoJSON order)

module.exports.sampleUsers = [
    // admin
    { username: 'admin',    email: 'admin@resq.in',          phone: '9876543210', role: 'admin',     password: 'Admin@1234' },
    // volunteers
    { username: 'ravi_v',   email: 'ravi.sharma@gmail.com',  phone: '9823456781', role: 'volunteer', password: 'Ravi@5678' },
    { username: 'priya_v',  email: 'priya.nair@gmail.com',   phone: '9712345678', role: 'volunteer', password: 'Priya@5678' },
    { username: 'arjun_v',  email: 'arjun.mehta@gmail.com',  phone: '9654321987', role: 'volunteer', password: 'Arjun@5678' },
    // citizens
    { username: 'suresh_c', email: 'suresh.kumar@gmail.com', phone: '9988776655', role: 'citizen',   password: 'Suresh@1234' },
    { username: 'anita_c',  email: 'anita.desai@gmail.com',  phone: '9871234567', role: 'citizen',   password: 'Anita@1234' },
    { username: 'mohd_c',   email: 'mohd.ali@gmail.com',     phone: '9765432109', role: 'citizen',   password: 'Mohd@1234' },
    { username: 'kavya_c',  email: 'kavya.reddy@gmail.com',  phone: '9856341278', role: 'citizen',   password: 'Kavya@1234' },
    { username: 'deepak_c', email: 'deepak.joshi@gmail.com', phone: '9734512678', role: 'citizen',   password: 'Deepak@1234' },
];

module.exports.sampleIncidents = [
    {
        title: 'Severe flooding in Kurla West residential area',
        description: 'Heavy monsoon rains have caused chest-deep flooding in Kurla West. At least 12 families are stranded on rooftops. Ground floor shops and homes are completely submerged. BEST buses have stopped service on LBS Marg. Residents are requesting immediate rescue boats.',
        category: 'flood',
        coordinates: [72.8777, 19.0728],
        address: 'LBS Marg, Kurla West, Mumbai, Maharashtra 400070',
        selfReportedSeverity: 'high',
        verifiedSeverity: 'high',
        priorityScore: 92,
        status: 'verified',
    },
    {
        title: 'Multi-storey building fire near Connaught Place',
        description: 'A fire broke out on the 4th floor of a commercial building near Connaught Place. Thick smoke is visible from Janpath. Fire brigade has been called but traffic congestion is delaying their arrival. Several office workers are trapped on upper floors.',
        category: 'fire',
        coordinates: [77.2195, 28.6329],
        address: 'Block F, Connaught Place, New Delhi 110001',
        selfReportedSeverity: 'high',
        verifiedSeverity: 'high',
        priorityScore: 95,
        status: 'verified',
    },
    {
        title: 'Partial building collapse in Dharavi',
        description: 'An old 3-storey chawl in Dharavi has partially collapsed after heavy rains weakened its foundation. Estimated 20 residents were inside at the time of collapse. Local volunteers are attempting to clear debris. NDRF has been alerted.',
        category: 'building collapse',
        coordinates: [72.8557, 19.0435],
        address: '90 Feet Road, Dharavi, Mumbai, Maharashtra 400017',
        selfReportedSeverity: 'high',
        verifiedSeverity: 'high',
        priorityScore: 98,
        status: 'verified',
    },
    {
        title: 'Flash flood blocking NH-44 near Nagpur',
        description: 'Sudden heavy downpour has caused flash flooding on NH-44 near Nagpur outskirts. Approximately 30 vehicles including buses and trucks are stranded. Water level is rising rapidly. Waist-deep water reported at the lowest point of the highway.',
        category: 'flood',
        coordinates: [79.0882, 21.1458],
        address: 'NH-44, Butibori, Nagpur, Maharashtra 441122',
        selfReportedSeverity: 'medium',
        verifiedSeverity: 'high',
        priorityScore: 80,
        status: 'verified',
    },
    {
        title: 'Minor earthquake tremors felt in Pune city',
        description: 'Mild earthquake tremors of approximately 3.8 magnitude were felt across Pune city. No major structural damage reported yet but residents of older buildings in Peth areas are panicking. Cracks observed in walls of a few heritage structures.',
        category: 'earthquake',
        coordinates: [73.8567, 18.5204],
        address: 'Shivajinagar, Pune, Maharashtra 411005',
        selfReportedSeverity: 'medium',
        verifiedSeverity: 'low',
        priorityScore: 35,
        status: 'verified',
    },
    {
        title: 'Slum fire in Govandi spreading rapidly',
        description: 'A fire started from a gas cylinder explosion in a hutment in Govandi and has spread to at least 40 shanties. Strong winds are aiding the spread. More than 200 people have been displaced. Two fire engines are on scene but water pressure is low.',
        category: 'fire',
        coordinates: [72.9218, 19.0479],
        address: 'Shivaji Nagar, Govandi, Mumbai, Maharashtra 400043',
        selfReportedSeverity: 'high',
        verifiedSeverity: 'high',
        priorityScore: 90,
        status: 'verified',
    },
    {
        title: 'Wall collapse at construction site in Bengaluru',
        description: 'A boundary wall at an under-construction building in Koramangala collapsed onto the road due to heavy rain, blocking traffic completely. No injuries reported yet but a two-wheeler is trapped under the debris. Road is dangerous.',
        category: 'building collapse',
        coordinates: [77.6245, 12.9352],
        address: '7th Block, Koramangala, Bengaluru, Karnataka 560095',
        selfReportedSeverity: 'medium',
        verifiedSeverity: null,
        priorityScore: null,
        status: 'pending',
    },
    {
        title: 'River Sabarmati overflowing near Ellis Bridge',
        description: 'The Sabarmati river has crossed the danger mark and is overflowing near Ellis Bridge in Ahmedabad. Waterfront promenade is fully submerged. Residents of low-lying areas on both banks have been advised to evacuate. Alerts issued for downstream villages.',
        category: 'flood',
        coordinates: [72.5873, 23.0225],
        address: 'Ellis Bridge, Ahmedabad, Gujarat 380006',
        selfReportedSeverity: 'high',
        verifiedSeverity: 'high',
        priorityScore: 88,
        status: 'verified',
    },
    {
        title: 'Gas leak reported at industrial unit in Surat',
        description: 'A toxic gas leak was reported at a textile dyeing unit in Sachin GIDC, Surat. Workers have been evacuated. Strong pungent smell is spreading in a 500-metre radius. Residents in adjacent society are experiencing eye and throat irritation.',
        category: 'other',
        coordinates: [72.8897, 21.0892],
        address: 'Sachin GIDC, Surat, Gujarat 394230',
        selfReportedSeverity: 'high',
        verifiedSeverity: null,
        priorityScore: null,
        status: 'pending',
    },
    {
        title: 'Roof collapse due to waterlogging in Hyderabad',
        description: 'The asbestos roof of a government school in Bandlaguda collapsed due to excessive rainwater accumulation. The incident happened at 7 PM so no students were present. However, adjoining classrooms are at risk. Urgent structural assessment needed.',
        category: 'building collapse',
        coordinates: [78.3908, 17.3616],
        address: 'Bandlaguda Jagir, Hyderabad, Telangana 500086',
        selfReportedSeverity: 'medium',
        verifiedSeverity: 'medium',
        priorityScore: 55,
        status: 'verified',
    },
];

module.exports.sampleShelters = [
    {
        name: 'NDRF Camp — Kurla Sports Ground',
        address: 'Near Kurla Railway Station, Kurla West, Mumbai, Maharashtra 400070',
        coordinates: [72.8791, 19.0724],
        totalCapacity: 500,
        currentOccupancy: 412,
        status: 'open',
    },
    {
        name: 'Municipal School Relief Camp — Dharavi',
        address: 'BMC School No. 7, 90 Feet Road, Dharavi, Mumbai, Maharashtra 400017',
        coordinates: [72.8540, 19.0450],
        totalCapacity: 300,
        currentOccupancy: 300,
        status: 'full',
    },
    {
        name: 'Red Cross Emergency Shelter — Connaught Place',
        address: 'Ram Manohar Lohia Hospital Campus, New Delhi 110001',
        coordinates: [77.2090, 28.6350],
        totalCapacity: 400,
        currentOccupancy: 187,
        status: 'open',
    },
    {
        name: 'Flood Relief Camp — Nagpur Butibori',
        address: 'Vidarbha Industries Association Ground, Butibori, Nagpur, Maharashtra 441122',
        coordinates: [79.0860, 21.1490],
        totalCapacity: 250,
        currentOccupancy: 198,
        status: 'open',
    },
    {
        name: 'Sabarmati Flood Camp — Ahmedabad',
        address: 'Sardar Patel Stadium, Navrangpura, Ahmedabad, Gujarat 380009',
        coordinates: [72.5592, 23.0330],
        totalCapacity: 600,
        currentOccupancy: 543,
        status: 'open',
    },
    {
        name: 'Community Hall Shelter — Koramangala',
        address: 'Koramangala Indoor Stadium, 3rd Block, Bengaluru, Karnataka 560034',
        coordinates: [77.6172, 12.9360],
        totalCapacity: 200,
        currentOccupancy: 45,
        status: 'open',
    },
    {
        name: 'Govandi Displaced Persons Camp',
        address: 'Deonar Dumping Ground Periphery, Govandi East, Mumbai, Maharashtra 400088',
        coordinates: [72.9280, 19.0520],
        totalCapacity: 350,
        currentOccupancy: 224,
        status: 'open',
    },
    {
        name: 'Hyderabad Bandlaguda Relief Centre',
        address: 'GHMC Community Hall, Bandlaguda Jagir, Hyderabad, Telangana 500086',
        coordinates: [78.3925, 17.3630],
        totalCapacity: 150,
        currentOccupancy: 0,
        status: 'closed',
    },
];

module.exports.sampleRequests = [
    {
        type: 'rescue',
        description: 'My elderly parents (ages 74 and 70) are stranded on the second floor of our house in Kurla. Ground floor is fully flooded. My father uses a wheelchair. We need a rescue boat urgently.',
        address: '34, Nehru Nagar, Kurla West, Mumbai, Maharashtra 400070',
        coordinates: [72.8760, 19.0701],
        urgency: 'high',
        status: 'assigned',
    },
    {
        type: 'medical',
        description: 'A pregnant woman in her 8th month is trapped in the Dharavi building collapse. She is experiencing labour pains. We urgently need a doctor and ambulance. The road is blocked with debris, please send a team on foot.',
        address: 'Kumbhar Wasti Lane 4, Dharavi, Mumbai, Maharashtra 400017',
        coordinates: [72.8562, 19.0428],
        urgency: 'high',
        status: 'open',
    },
    {
        type: 'food',
        description: 'Around 60 people who have taken shelter under the flyover near Govandi station have not received any food or water for 18 hours. There are children and infants among them. Requesting immediate food packets and drinking water.',
        address: 'Under Govandi Flyover, Shivaji Nagar, Govandi, Mumbai 400043',
        coordinates: [72.9195, 19.0455],
        urgency: 'high',
        status: 'open',
    },
    {
        type: 'water',
        description: 'The flood water has contaminated our borewell. Approximately 500 residents of this colony have no access to drinking water. We have been managing with stored water which is now exhausted. Need water tanker urgently.',
        address: 'Ambedkar Nagar, Butibori, Nagpur, Maharashtra 441122',
        coordinates: [79.0840, 21.1440],
        urgency: 'high',
        status: 'open',
    },
    {
        type: 'shelter',
        description: 'Our entire family of 8 including 3 children has been displaced by the fire in Govandi. We lost everything. We need shelter and basic necessities — clothes, blankets, and food. We are currently at the BEST bus depot.',
        address: 'BEST Bus Depot, Govandi West, Mumbai, Maharashtra 400043',
        coordinates: [72.9210, 19.0468],
        urgency: 'medium',
        status: 'resolved',
    },
    {
        type: 'rescue',
        description: 'Five workers are stuck inside a flooded basement of a building in Connaught Place. The gate has jammed due to water pressure. Water level is rising. Emergency pumping equipment needed immediately.',
        address: 'Basement Parking, N Block, Connaught Place, New Delhi 110001',
        coordinates: [77.2178, 28.6311],
        urgency: 'high',
        status: 'assigned',
    },
    {
        type: 'medical',
        description: 'An elderly man (approx 65 years) collapsed near Ellis Bridge possibly due to heat and panic during flood evacuation. He is semi-conscious with laboured breathing. No ambulance is accessible due to flooded roads. We need medical aid on boat.',
        address: 'Near Ellis Bridge, Riverfront West, Ahmedabad, Gujarat 380006',
        coordinates: [72.5860, 23.0218],
        urgency: 'high',
        status: 'open',
    },
    {
        type: 'food',
        description: 'Residents of 3 apartment buildings in Koramangala are stuck since yesterday after the road was blocked by the wall collapse. Grocery shops are unreachable. Around 150 residents need food and essential supplies for at least 2 days.',
        address: '7th Block, Koramangala, Bengaluru, Karnataka 560095',
        coordinates: [77.6250, 12.9348],
        urgency: 'medium',
        status: 'open',
    },
    {
        type: 'other',
        description: 'The gas leak at Sachin GIDC is causing severe breathing difficulty for residents of nearby Swaminarayan Society. At least 10 people including 3 children are experiencing nausea and dizziness. Request hazmat team and medical first responders.',
        address: 'Swaminarayan Society, Sachin, Surat, Gujarat 394230',
        coordinates: [72.8880, 21.0875],
        urgency: 'high',
        status: 'open',
    },
    {
        type: 'water',
        description: 'The pipeline serving Bandlaguda colony burst due to pressure after the roof collapse incident. No running water for past 24 hours. Approximately 200 households affected. Need water tankers and pipeline repair team.',
        address: 'Bandlaguda Colony, Hyderabad, Telangana 500086',
        coordinates: [78.3900, 17.3610],
        urgency: 'medium',
        status: 'open',
    },
];
